# Generated by Django 5.0.3 on 2024-04-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_estimation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driven_kilometer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='max_power',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
